server:
  port: 8082
  servlet:
    context-path: /authadmin

mybatis-plus:
  mapperLocations: classpath:mappers/**/*.xml

auth.server.uri: http://localhost:8081/uac

security:
  oauth2:
    client.clientId: devops
    client.clientSecret: devops
    client.user-authorization-uri: ${auth.server.uri}/oauth/authorize
    client.access-token-uri: ${auth.server.uri}/oauth/token
    resource.jwt.key-uri: ${auth.server.uri}/oauth/token_key
    authorization.check-token-access: ${auth.server.uri}/oauth/check_token

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://210.12.14.114:8095/hyc_v2?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: huiyunche
    password: )9AG&a2hg+t^V83

    # 连接池初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxIdel: 15
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    #生产环境要改为true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat=true

#log
logging:
  config: classpath:logback/dev/logback.xml
